language:
 - en
 - cn
 - tw
 - ja
langselect:
  enable: true
options: # langselect button display options
    en: English
    ja: 日本語
    ## cn: 简体中文
    ## tw: 正體中文

name: YM

menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

favicon: /css/favicon.png
logo: /css/logo-60.png

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright: 
  since: 
  name:
  url:
