name: YM

menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

favicon: /css/favicon.png
logo: 

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright: 
  since: 
  name:
  url:
